- hosts: all 
  become: true
  tasks:
  - name: Install Httpd package 
    yum:
      name: httpd 
      state: latest
  - name: Start service httpd 
    service:
      name: httpd 
      state: started 
      enabled: true 
