cfme_ip: 10.10.39.30   # The IP address or the hostname of the appliance holding the API 
owner_email: rhamdi@rehat.com
#vm_name: testapi59
#cpus: 1 
#memory: 1024
#template_guid: 241b8a86-3889-46e3-8f9d-da4f94bdd601
template_guid: 16a0be30-c322-41a4-b56a-2da2d63921b9 
catalog_id: 1000000000001 
bootstrap_service_id: 1000000000005
